name: note_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.0.0          # Kimlik doğrulama için
  cloud_firestore: ^5.0.0         # Firestore için
  supabase: ^2.0.0                # Supabase için (versiyonu kontrol et)
  provider: ^6.0.0                # Durum yönetimi için
  shared_preferences: ^2.0.0      # Yerel veri saklama için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png           # Logo için
    - assets/avatar.png         # Avatar için
